server:
  port: 8082

spring:
  datasource:
    name: pis
    url: jdbc:mysql://114.116.154.251:3306/riskm?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #         使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    elasticsearch:
#      cluster-nodes: 114.116.154.251:9200
#      cluster-name: elasticsearch



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
swagger:
  enabled: true
  title: offline-work api 文档
  description: offline-work api 文档
  version: 0.0.1
  base-package: com.lc.controller
  base-path: /**
  exclude-path: /error
  ui-config:
    json-editor: true